<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Stripe;


class StripeController extends Controller
{
    public function index(){
        return view('stripe');
    }

    public function stripepay(Request $request){

        Stripe\Stripe::setApiKey(env('STRIPE_SECRET'));

        Stripe\Charge::create([
            "amount" => 3000, // Amount in cents
            "currency" => "usd",
            "source" => $request->stripeToken, // The token generated by Stripe.js
            "description" => "Customer name is" . $request->name. "and Payment Type is" 
            . $request->payment_type
        ]);
        return back()->with('success', 'Payment successful!');
    }
}
